version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./src:/opt/paygo
    depends_on:
      - db
 
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    container_name: paygo-server-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpass
      MYSQL_PASSWORD: nonstop12
      MYSQL_USER: paygouser
      MYSQL_DATABASE: paygodb
    volumes:
      - mysqldata:/var/lib/mysql

networks:
  default:
    external:
      name: gititdocs

volumes:
  mysqldata:
    driver: local

