variables:
        SERVICE_NAME: app

stages:
        - deploy

docker-build:
        stage: deploy
        image: docker:latest
        tags:
                - aws-box1
        only:
                - main
                - develop
        services:
                - name: docker:19.03.8-dind
        script:
                - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
                - docker-compose build --pull app
                - docker-compose push app

deploy:
        stage: deploy
        image: docker:latest
        tags:
                - aws-box1
        only:
                - main
                - develop
        services:
                - name: docker:19.03.8-dind
        script:
                - docker-compose up -d
        dependencies:
                - docker-build
